---
ansible_connection: local

#
# OpenShift
#
api_url: 'https://api.lab.linsol.local:6443'
api_key: "{{ vault_api_key }}"

#
# Labels
#
env: dev
app: voting

#
# Project
#
project_name: "{{ dev_namespace }}"
manage_projects: false
redhat_io_pull_token: "{{ vault_redhat_io_pull_token }}"
quay_push_passwd: 'we_dont_want_to_push_from_dev'
quay_push_user: 'we_dont_want_to_push_from_dev'

#
# Database
#
#db_name: voting
#db_user: "{{ vault_db_user }}"
#db_password: "{{ vault_db_password }}"
#db_root_password: "{{ vault_db_root_password }}"


#
# API
#
#api_build: true
#api_source_repository_ref: 'master'
#api_source_repository_url: 'https://gitlab.com/voting/voting.git'
#api_replicas: 1
#api_image: "{{ app }}-api:latest"
#api_fqdn: 'api-dev.voting.net'
#api_gitlab_webhook_secret_key: "{{ vault_api_gitlab_webhook_secret_key }}"

#
# Pipelines
#
# We don't need Jenkis for Dev
#jenkins_replicas: 0

#
# Certbot
#
#cb_extra_opts: ''
#cb_email: "{{ vault_cb_email }}"

#
# Pipelines
#
#create_jenkis: false
