---
state: present
app: vote
vote_build_image: 'python'
vote_python_version: '2.7'
vote_source_repository_ref: 'master'
vote_source_repository_url: 'https://github.com/LinSol-Ltd/voting-app.git'
vote_gitlab_webhook_secret: 'glsecret'
vote_replicas: 1
vote_image: "{{ app }}-vote"
vote_image_tag: latest
vote_fqdn: vote.linsol.co.uk
vote_build: true
vote_hpa_min_replicas: 1
vote_hpa_max_replicas: 6
vote_hpa_target_cpu_utilization_percentage: 50
vote_memory_limit: "256Mi"
